# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Run any pre-build commands if needed
      - python -m pip install --upgrade pip

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Submodules configuration
submodules:
  include: all
  recursive: true

# Search configuration
search:
  ranking:
    # Higher values move documents up in results
    api/*: 2
    guides/*: 5
    
# Additional formats - set to all to build PDF, EPUB, and HTML
formats:
  - htmlzip
  - pdf
